// Common lockfiles and machine-generated artifacts surfaced in the Review Hub.
// Matches conservatively — d.ts is excluded because hand-authored type
// declarations are common; CHANGELOG.md is excluded because it's frequently
// hand-edited despite being generated by some tooling.

const GENERATED_BASENAMES = new Set<string>([
  "package-lock.json",
  "yarn.lock",
  "pnpm-lock.yaml",
  "bun.lockb",
  "composer.lock",
  "Gemfile.lock",
  "Cargo.lock",
  "Pipfile.lock",
  "poetry.lock",
  "go.sum",
]);

const GENERATED_EXT_RE =
  /\.(?:lock|min\.js|min\.css|min\.mjs|snap|pb\.go|pb\.ts|pb\.d\.ts|generated\.[^.]+)$/i;

const GENERATED_DIR_RE = /(?:^|\/)(?:dist|build|\.next|\.nuxt|\.svelte-kit|\.out|coverage)\//;

export function isGeneratedFile(filePath: string): boolean {
  if (!filePath) return false;
  const normalized = filePath.replace(/\\/g, "/");
  const base = normalized.split("/").pop() ?? "";

  if (GENERATED_BASENAMES.has(base)) return true;
  if (GENERATED_EXT_RE.test(base)) return true;
  if (GENERATED_DIR_RE.test(normalized)) return true;

  return false;
}
