/**
 * Terminal Activity Types
 *
 * Types for semantic terminal activity detection.
 * Enables human-readable status updates and terminal classification.
 */

/**
 * Terminal task classification types.
 * - interactive: Short-lived commands, REPLs, prompts requiring user input
 * - background: Long-running processes (dev servers, watchers, databases)
 * - idle: Completed tasks with no activity
 */
export type TerminalTaskType = "interactive" | "background" | "idle";

/**
 * Terminal activity status.
 * - working: Terminal is actively processing
 * - waiting: Terminal is waiting for user input
 * - success: Task completed successfully
 * - failure: Task failed or encountered an error
 */
export type TerminalActivityStatus = "working" | "waiting" | "success" | "failure";

/**
 * Semantic activity information for a terminal.
 * Generated by AI analysis of recent terminal output.
 */
export interface TerminalActivity {
  /** Terminal identifier */
  terminalId: string;

  /** Human-readable status (max 6 words, active voice) */
  headline: string;

  /** Current operational status */
  status: TerminalActivityStatus;

  /** Terminal classification for UI/UX decisions */
  type: TerminalTaskType;

  /** AI confidence in classification (0.0 to 1.0) */
  confidence: number;

  /** Unix timestamp when analysis was performed */
  timestamp: number;
}

/**
 * Payload for terminal:activity IPC event.
 * Extends TerminalActivity with optional context fields.
 */
export interface TerminalActivityPayload extends TerminalActivity {
  /** Associated worktree ID (if applicable) */
  worktreeId?: string;
}
